// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models
{
    public partial class CourseName
    {
        public CourseName()
        {
            CourseLists = new HashSet<CourseList>();
        }

        public int Id { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public string Txtmore { get; set; }

        public virtual ICollection<CourseList> CourseLists { get; set; }
    }
}