// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models
{
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Userpass { get; set; }
        public string Rolename { get; set; }
        public int? UniId { get; set; }
        public DateTime? CrDate { get; set; }
    }
}