// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models;

public partial class CourseList
{
    public int Id { get; set; }

    public int? CourseId { get; set; }

    public int? GLId { get; set; }

    public virtual CourseName Course { get; set; }
}