// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models;

public partial class GroupLesson
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Logo { get; set; }

    public int? TeacherId { get; set; }

    public int? UniId { get; set; }

    public DateTime? Txtdatetime { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();
}