// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models;

public partial class Lesson
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ViewMinut { get; set; }

    public string Txtmore { get; set; }

    public string Txtcontent { get; set; }

    public int? GId { get; set; }

    public int? TeacherId { get; set; }

    public virtual GroupLesson GIdNavigation { get; set; }
}