// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace edu.Models
{
    public partial class Lesson
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Сэдэвийн нэр ээ оруулна уу!")]
        [Display(Name = "Сэдэвийн нэр")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Үргэлжлэх хугацаа оруулна уу!")]
        [Display(Name = "Үргэлжлэх хугацаа нэр")]
        public int? ViewMinut { get; set; }
        [Display(Name = "Товч")]
        public string Txtmore { get; set; }
        [Display(Name = "Агуулга")]
        public string Txtcontent { get; set; }
        [Display(Name = "Дуу, сонсох")]
        public string Txtvoice { get; set; }
        [Display(Name = "Видео ")]
        public string Txtvideo { get; set; }
        [Display(Name = "Дасгал")]
        public string Txtwork { get; set; }
        public int? GId { get; set; }
        public int? TeacherId { get; set; }
        [Display(Name = "Огноо")]
        public DateTime? CreateDate { get; set; }
    }
}