// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace edu.Models
{
    public partial class NewsCat
    {
        public NewsCat()
        {
            NewsLists = new HashSet<NewsList>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Категори нэр ээ оруулна уу!")]
        [Display(Name = "Категори нэр ")]
        public string Txtname { get; set; }
        [Display(Name = "Дараалал ")]
        public int? TxtOrd { get; set; }
        [Display(Name = "Товч ")]
        public string Txtmore { get; set; }
        [Display(Name = "Агуулга ")]
        public string Txtcontent { get; set; }
        public int? SubId { get; set; }
        [Display(Name = "Огноо ")]

        public DateTime? TxtDate { get; set; }
        [Display(Name = "Төрөл ")]

        public int? Txttype { get; set; }
        [Display(Name = "Холбоос ")]

        public string Txtlink { get; set; }
        [Display(Name = "Нуух эсэх ")]

        public long? Vis { get; set; }

        public virtual ICollection<NewsList> NewsLists { get; set; }
    }
}