// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models;

public partial class NewsCat
{
    public int Id { get; set; }

    public string Txtname { get; set; }

    public long? Vis { get; set; }

    public int? TxtOrd { get; set; }

    public int? SubId { get; set; }

    public string Txtmore { get; set; }

    public string Txtcontent { get; set; }

    public DateTime? TxtDate { get; set; }

    public virtual ICollection<NewsList> NewsLists { get; set; } = new List<NewsList>();
}