// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models
{
    public partial class NewsList
    {
        public int Id { get; set; }
        public string Txtname { get; set; }
        public string Txtmore { get; set; }
        public string Txtcontent { get; set; }
        public string Txtdate { get; set; }
        public int? CatId { get; set; }
        public DateTime? Txtdatetime { get; set; }

        public virtual NewsCat Cat { get; set; }
    }
}