// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edu.Models;

public partial class University
{
    public int Id { get; set; }

    public string Uniname { get; set; }

    public string UninameShort { get; set; }

    public string UniLogo { get; set; }
}